import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, SignInButton, UserButton, useUser } from "@clerk/nextjs";
import Header from "@/components/header";
import Landing from "@/components/landing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: '#4B4AEF' },
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}>
      <html lang="en">
        <body className="font-Poppins">         
          <SignedOut>
            <Landing />
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
